version: "3"
services:
  lb:
    image: nginx
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
      - 443:443
    networks:
      - oktopus
  api:
    image: my-api
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    volumes:
      - "/srv/data/mydatabase:/srv/data/mydatabase"
    networks:
      - oktopus
  frontend:
    image: my-frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - oktopus
 
 
networks:
  oktopus: