 
version: "3"
services:
  reverseproxy:
    image: mylb
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    ports:
      - 80:80    
      - 443:443
    networks:
      - moneyboard
  api:
    image: myapi
    volumes:
      - /home/wesley/moneyboard/data:/var/www/api/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
     
    networks:
      - moneyboard
  frontend:
    image: myfrontend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure   
    networks:
      - moneyboard
 
volumes:
  certs:
  certs-data:

networks:
  moneyboard: